namespace Windows32
{
	public enum enumDCConst
	{
		DC_DRIVERVERSION = 0,
		DC_TECHNOLOGY = 2,
		DC_HORZSIZE = 4,
		DC_VERTSIZE = 6,
		DC_HORZRES = 8,
		DC_VERTRES = 10,
		DC_LOGPIXELSX = 88,
		DC_LOGPIXELSY = 90,
		DC_PLANES = 14,
		DC_NUMBRUSHES = 0x10,
		DC_NUMCOLORS = 24,
		DC_NUMFONTS = 22,
		DC_NUMPENS = 18,
		DC_ASPECTX = 40,
		DC_ASPECTXY = 44,
		DC_ASPECTY = 42,
		DC_PDEVICESIZE = 26,
		DC_CLIPCAPS = 36,
		DC_SIZEPALETTE = 104,
		DC_NUMRESERVED = 106,
		DC_COLORRES = 108,
		DC_PHYSICALOFFSETX = 112,
		DC_PHYSICALOFFSETY = 113,
		DC_PHYSICALHEIGHT = 111,
		DC_PHYSICALWIDTH = 110,
		DC_SCALINGFACTORX = 114,
		DC_SCALINGFACTORY = 115,
		DC_LISTEN_OUTSTANDING = 1,
		DC_CURVECAPS = 28,
		DC_LINECAPS = 30,
		DC_POLYGONALCAPS = 0x20,
		DC_TEXTCAPS = 34
	}
}
