namespace Windows32
{
	public enum HitTest
	{
		HTERROR = -2,
		HTTRANSPARENT = -1,
		HTNOWHERE = 0,
		HTCLIENT = 1,
		HTCAPTION = 2,
		HTSYSMENU = 3,
		HTGROWBOX = 4,
		HTSIZE = 4,
		HTMENU = 5,
		HTHSCROLL = 6,
		HTVSCROLL = 7,
		HTMINBUTTON = 8,
		HTMAXBUTTON = 9,
		HTLEFT = 10,
		HTRIGHT = 11,
		HTTOP = 12,
		HTTOPLEFT = 13,
		HTTOPRIGHT = 14,
		HTBOTTOM = 0xF,
		HTBOTTOMLEFT = 0x10,
		HTBOTTOMRIGHT = 17,
		HTBORDER = 18,
		HTREDUCE = 8,
		HTZOOM = 9,
		HTSIZEFIRST = 10,
		HTSIZELAST = 17,
		HTOBJECT = 19,
		HTCLOSE = 20,
		HTHELP = 21
	}
}
