//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Writer.WinFormDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03708C034804000000001B000000E983BDE6988CE4BFA1E681AFE58685E983A8E6B58BE8AF95E7898" +
            "8CE3500004D751B000000E983BDE6988CE4BFA1E681AFE58685E983A8E6B58BE8AF95E789880F000" +
            "0001C0090536205")]
        public string WriterRegisterCode {
            get {
                return ((string)(this["WriterRegisterCode"]));
            }
            set {
                this["WriterRegisterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03708C034804000000001B000000E983BDE6988CE4BFA1E681AFE58685E983A8E6B58BE8AF95E7898" +
            "8CE3500004D751B000000E983BDE6988CE4BFA1E681AFE58685E983A8E6B58BE8AF95E789880F000" +
            "0001C0090536205")]
        public string TimeLineRegisterCode {
            get {
                return ((string)(this["TimeLineRegisterCode"]));
            }
            set {
                this["TimeLineRegisterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"03C98C034804000000003D000000E58D97E4BAACE983BDE6988CE4BFA1E681AFE7A791E68A80E69C89E99990E585ACE58FB832303137E5B9B4E5BAA6E6B58BE8AF95E78988E68E88E69D8337360000AC7C3D000000E58D97E4BAACE983BDE6988CE4BFA1E681AFE7A791E68A80E69C89E99990E585ACE58FB832303137E5B9B4E5BAA6E6B58BE8AF95E78988E68E88E69D830F0000003C00D1679ABB")]
        public string FriedmanCurveRegisterCode {
            get {
                return ((string)(this["FriedmanCurveRegisterCode"]));
            }
            set {
                this["FriedmanCurveRegisterCode"] = value;
            }
        }
    }
}
