using System.ComponentModel;
using System.Runtime.InteropServices;

namespace AxNsoOfficeLib
{
	                                                                    /// <summary>
	                                                                    ///       控件属性
	                                                                    ///       </summary>
	[ComVisible(false)]
	public enum ControlProp
	{
		[Description("第一版ID")]
		Id,
		[Description("第二版ID")]
		ID,
		[Description("第一版元素ID")]
		ControlID,
		[Description("第二版元素ID")]
		ElementID,
		[Description("元素唯一编码")]
		Code,
		[Description("版本")]
		WordVersion,
		[Description("外部数据源")]
		ExternalDataSourceId,
		[Description("上方标题")]
		HelpTip,
		[Description("是否允许删除")]
		DelFlag,
		[Description("是否只读")]
		EditProtect,
		[Description("是否保存到节点表")]
		IsSaveAsNode,
		[Description("是否生成到XML(强制生成节点 否则word会不能打印此元素)")]
		IsNotRecordInXML,
		[Description("是否必填")]
		MustFillContent,
		[Description("是否引用前回值")]
		Reference,
		[Description("是否可扩展输入")]
		ExpandInput,
		[Description("是否显示边框")]
		Edge,
		[Description("是否女用")]
		WomanUse,
		[Description("元素类型")]
		ControlType,
		[Description("元素原始类型")]
		ControlTypeTemplate,
		[Description("是否隐藏")]
		IsCtrlHidden,
		[Description("是否保密浏览")]
		ViewSecret,
		[Description("元素名称")]
		ControlName,
		[Description("首次更新")]
		UpdateFirst,
		[Description("每次更新")]
		UpdateEveryTime,
		[Description("是否做成组套元素")]
		IsGroupUse,
		[Description("是否应用于组套替换")]
		IsGroupReplace,
		[Description("是否使用默认时间")]
		IsDefault,
		[Description("占位符")]
		PlaceHolder,
		[Description("备选项")]
		Reserve,
		[Description("自定义属性")]
		UserSet,
		[Description("左边框")]
		EdgeStyle,
		[Description("右边框")]
		EdgeStyle2,
		[Description("元素一致性")]
		ConsistenceType,
		[Description("单选框文本")]
		CheckboxCaption,
		[Description("元素组")]
		ELementSection,
		[Description("段落")]
		ELementRegion,
		[Description("文档")]
		Document,
		[Description("元素组ID")]
		ELementSectionID,
		[Description("段落ID")]
		ELementRegionID,
		[Description("文档ID")]
		DocumentID,
		[Description("转换类")]
		FormatConvertClassWord,
		[Description("转换节点")]
		FormatConvertClassNode,
		[Description("XML节点字符串")]
		XmlNodeString,
		[Description("元素计算表达式")]
		CalcText,
		[Description("控件自定义返回内容")]
		ShowControlCustom,
		[Description("区域属性--编辑保护")]
		bEditProtect,
		[Description("区域属性--删除保护")]
		bDeleteProtect,
		[Description("区域属性--是否显示")]
		bVisible,
		[Description("区域属性--是否在只读范围内可编辑")]
		bEditInReadOnly,
		[Description("区域属性--人员类型 医生D 护士N")]
		EmployeeType,
		[Description("区域名称")]
		RegionName,
		[Description("区域所在行号")]
		RegionLineNum,
		[Description("区域属性-病程创建时间")]
		RegionCreatTime,
		[Description("区域属性-病程记录名称")]
		RegionProgressName,
		[Description("区域属性-病程记录DataId")]
		RegionProgressDataId,
		[Description("区域属性-病程记录Id")]
		RegionProgressId,
		[Description("区域属性-导航信息显示")]
		RegionPropertyContent,
		[Description("区域属性-病历名称")]
		RegionFloatInform,
		[Description("区域属性-页眉信息")]
		RegionHeader,
		[Description("区域属性-是否参与页眉显示")]
		RegionIsShowHeader,
		[Description("区域属性-区域的起始页")]
		RegionStartPage,
		[Description("节属性-标识-三级联动使用")]
		Mark,
		[Description("控件使用场景")]
		Tag,
		[Description("元素内容不为空时是否不打印")]
		IsNullPrint,
		[Description("是否替换原有值")]
		ReplaceOldValue,
		[Description("元素的显示格式")]
		ResultType,
		[Description("是否在入院和出院时间之间")]
		BetweenInTimeAndOutTime,
		[Description("是否可以提前书写")]
		WritingInAdvance,
		[Description("表格打印单元格集合")]
		PrintCells,
		[Description("表格行打印标记ControlId")]
		PrintFlagControlId
	}
}
