//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Writer.WinFormDemo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.Writer.WinFormDemo.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在该名称的书签,无法执行操作. 的本地化字符串。
        /// </summary>
        internal static string _BOOKMARKEXIST {
            get {
                return ResourceManager.GetString("_BOOKMARKEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误: 的本地化字符串。
        /// </summary>
        internal static string _ERROR {
            get {
                return ResourceManager.GetString("_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行命令错误: 的本地化字符串。
        /// </summary>
        internal static string _EXEERR {
            get {
                return ResourceManager.GetString("_EXEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMP,PNG,JPG,GIF图片文件|*.bmp;*.png;*.jpg;*.jpeg;*.gif|所有文件|*.* 的本地化字符串。
        /// </summary>
        internal static string _IMGFILTER {
            get {
                return ResourceManager.GetString("_IMGFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 页 第 {1} 行 第 {2} 列 的本地化字符串。
        /// </summary>
        internal static string _LINE {
            get {
                return ResourceManager.GetString("_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功打开文件  的本地化字符串。
        /// </summary>
        internal static string _OPENED {
            get {
                return ResourceManager.GetString("_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件“{0}” 错误:{1} 的本地化字符串。
        /// </summary>
        internal static string _OPENERR {
            get {
                return ResourceManager.GetString("_OPENERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在打开文件  的本地化字符串。
        /// </summary>
        internal static string _OPENING {
            get {
                return ResourceManager.GetString("_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用HTML代码缩进处理? \r\n使用缩进处理的HTML代码便于阅读和修改,但可能导致HTML页面显示和文本编辑器中的显示样式有所差别. 的本地化字符串。
        /// </summary>
        internal static string _QUERYHTMLINDENT {
            get {
                return ResourceManager.GetString("_QUERYHTMLINDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已修改，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string _QUERYSAVE {
            get {
                return ResourceManager.GetString("_QUERYSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功保存文件  的本地化字符串。
        /// </summary>
        internal static string _SAVED {
            get {
                return ResourceManager.GetString("_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件“{0}” 错误:{1} 的本地化字符串。
        /// </summary>
        internal static string _SAVEERR {
            get {
                return ResourceManager.GetString("_SAVEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RTF文件,TXT文件,XML文件|*.rtf;*.xml;*.txt|所有文件|*.* 的本地化字符串。
        /// </summary>
        internal static string _SAVEFILTER {
            get {
                return ResourceManager.GetString("_SAVEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存文件  的本地化字符串。
        /// </summary>
        internal static string _SAVING {
            get {
                return ResourceManager.GetString("_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  选择了{0}个元素 的本地化字符串。
        /// </summary>
        internal static string _SELECTELEMENTS {
            get {
                return ResourceManager.GetString("_SELECTELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XWriterLib 演示 的本地化字符串。
        /// </summary>
        internal static string _TEXTDEMO {
            get {
                return ResourceManager.GetString("_TEXTDEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计信息 _____________
        ///页数              {0}
        ///字数              {1}
        ///字符数(不计空格)  {2}
        ///字符数(计空格)    {3}
        ///段落数            {4}
        ///行数              {5} 的本地化字符串。
        /// </summary>
        internal static string _WORDCOUNT {
            get {
                return ResourceManager.GetString("_WORDCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档内容校验通过。 的本地化字符串。
        /// </summary>
        internal static string DocumentValidate {
            get {
                return ResourceManager.GetString("DocumentValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap png_0460 {
            get {
                object obj = ResourceManager.GetObject("png_0460", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除记录? 的本地化字符串。
        /// </summary>
        internal static string PromptDeleteRecord {
            get {
                return ResourceManager.GetString("PromptDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此处演示在后台将XDesigner.Writer格式的XML文档转换为RTF文档，不显示用户界面，可以运用在ASP.NET或Service程序中。 的本地化字符串。
        /// </summary>
        internal static string PromptXML2RTF {
            get {
                return ResourceManager.GetString("PromptXML2RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个XDesigner.Writer程序保存的XML文件 的本地化字符串。
        /// </summary>
        internal static string SOURCEXMLDLGTITLE {
            get {
                return ResourceManager.GetString("SOURCEXMLDLGTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功的将”{0}“转换为”{1}“。 的本地化字符串。
        /// </summary>
        internal static string SUCCESSXML2RTF_SOURCE_DESC {
            get {
                return ResourceManager.GetString("SUCCESSXML2RTF_SOURCE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
    }
}
