using Microsoft.Win32;

namespace HDF.Framework.Test
{
    internal class AutoGetDump
    {

        static void AutoGenerateDumpWhenCrash()
        {

            //参考文档：https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps?redirectedfrom=MSDN 

            //注册表里，添加【程序崩溃后，自动生成dump文件配置】
            //注册表需要admin权限！
            try
            {
                var outputDmpPath = AppDomain.CurrentDomain.BaseDirectory + "Dump";
                if (!Directory.Exists(outputDmpPath))
                {
                    Directory.CreateDirectory(outputDmpPath);
                }

                var fileName = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
                var processName = fileName.Substring(fileName.LastIndexOf('\\') + 1);

                //注册表地址
                string regPath = @"SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\" + processName;
                var reg = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64);//Registry64防止注册表重定向到wow64

                var subKey = reg.CreateSubKey(regPath);



                subKey.SetValue("DumpCount", 1, RegistryValueKind.DWord);//dump文件个数
                subKey.SetValue("DumpFolder", outputDmpPath, RegistryValueKind.ExpandString);//dump文件目录
                subKey.SetValue("DumpType", 2, RegistryValueKind.DWord);//dump文件类型

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                return;
            }


        }

    }
}
